### PR TITLE
Add MILP backend

### PR DESCRIPTION
**Pull request by dirkschumacher**
#170 Work in progress

### CODE REVIEW

**Comment by dirkschumacher** [comment]
@kkmann, re #166: if you work with large models, would you like to give `MILPModel` a try? With larger models, I saw a speedup of up to 1000x compared to the old backend.

Here is an example: https://gist.github.com/dirkschumacher/6ffe67da7aa83c41a1ea15fb29961dde

**Comment by rickyars** [comment]
@dirkschumacher I've been trying to convert my models to use the new back-end but I'm getting really confused. I read the new docs, focusing on the section about vectorized inputs. I think I understand the change, but there are two things that don't make sense. The first is `colwise` and why we need to use it in the traveling salesman example. Previously we would have just multiplied the matrix by the variables. The second is this whole business here:
```
distance <- as.matrix(stats::dist(select(cities, x, y), diag = TRUE, upper = TRUE))
dist_fun <- function(i, j) {
  vapply(seq_along(i), function(k) distance[i[k], j[k]], numeric(1L))
}
```
How does this work? Again, in the `MIPModel` we woudl have just mulplied the `distance` matrix by the variables, but now we need this in addition to a `colwise`:
```
set_objective(sum_expr(colwise(dist_fun(i, j)) * x[i, j], i = 1:n, j = 1:n), "min")
```
Any tips would be appreciated.

**Comment by dirkschumacher** [comment]
@rickyars with the current semantic, multiplying an indexed variable by a vector applies the multiplication to each row. If instead you would like to multiply with each column, you need to mark one operand with colwise.

The reason you cannot use `matrix[i, j]` anymore is that `i` and `j` are now vectors. Indexing a matrix by a vector yields something different.

**Comment by dirkschumacher** [comment]
But I take this as evidence that this is not clear and that I need to better document it or find a better solution.

**Pull request merged**
