### PR TITLE
modified status

### PR DESCRIPTION
**Pull request by rickyars**
status is now a list containing the status code and message from the solver

### CODE REVIEW

**Comment by rickyars** [comment]
@dirkschumacher what do you think of this change? this is something i really need for my work. even when we get a non-optimal solution, i need to keep the solutions.

**Comment by dirkschumacher** [comment]
@rickyars will look at it soon.

**Comment by rickyars** [comment]
@dirkschumacher one thing to note is that this also requires changes to the `ompr.roi` package. I've also submitted a pull request over there: https://github.com/dirkschumacher/ompr.roi/pull/18

**Comment by hugolarzabal** [comment]
These changes are quite usefull.

I tried this branch after merging it with the master and it seems to work well (a few tests need to be edited)

I have a few suggestions:

- Be carefull, different solvers do not behave the same way regarding the code they return, for exemple, symphony always return 1 when stopped with a time limit and cbc always return 0 regardless of the fact that they found a feasible solution or not. (I do not think anything cna be done about it in ompr)
- Maybe the statut$msg should contain all the information from the solver (status$msg) instead of just the message (status$msg$message)
- Wouldn't it be a little bit more clear if the code were translated as "solved"/ "not solved" instead of 0/1 ?

**Comment by hugolarzabal** [comment]
To be clear, the solvers always return 0 for solved and 1 for unsolved but some solvers consider that a problem stopped on time limit (or for other reason) is solved and others consider it unsolved.

**Comment by dirkschumacher** [comment]
Sorry for stalling this discussion. I thought about that issue again and wrote PR #384 . This PR enables adding additional information to the solution object. Which is solver specific and does not depend on any ompr data format. This can be used in {ompr.roi} to store the full, raw solver message.

Thanks again for your effort back then @rickyars !

**Pull request closed without merging**
