### PR TITLE
Implement methods for LaTeX model output

### PR DESCRIPTION
**Pull request by benjcunningham**
Addresses #7 by implementing a function to convert a model element (i.e., an arbitrary R `expression` object) to an equivalent LaTeX command. Return values are either character strings or `knit_asis` objects (for easy use in R Markdown docs). Convenience methods for outputting objective functions and constraints are also included.

As a quick demo, my intent was for these functions to sit at the end of an R Markdown chunk like:

```r
model <- MIPModel() %>% ...

# Un-expanded objective
knitr_objective(model)

# We can wrap the output in arbitrary LaTeX and
# collapse constraints on with newlines, commas, etc.
knitr_constraints(model, fmt = "\\begin{gather*}%s\\end{gather*}", collapse = ", \\\\")
```

I'd still consider this a WIP, but hopefully it is on the right track to what was initially requested in the issue. I would especially appreciate feedback on the API; I imagined separating the generalized function + convenience methods would be helpful, but perhaps they could be combined. Either way, if (or as) the internals are restructured, I think most of the tools should be here now to support outputting other useful elements (e.g. non-expanded constraints or even the full model).

Happy to also provide a vignette demoing usage further, if necessary; I realize tests and code snippets only show half the story when it comes to the LaTeX output.

### CODE REVIEW

**Comment by dirkschumacher** [comment]
First of all: very cool and thanks for the initiative! 
I will have more time towards the weekend to look at it in more detail.

Just skimming over it it would be nice if you removed the pipe `%>%` operator.
Second quick comment is: can you use S3 generic methods for the `optimization_model` class instead of normal functions?

**Comment by benjcunningham** [comment]
Sorry for the delay. Getting started on these comments now.

> Just skimming over it it would be nice if you removed the pipe `%>%` operator.

Will do.

> Second quick comment is: can you use S3 generic methods for the `optimization_model` class instead of normal functions?

Sure, but just to make sure I understand: I could now see this going a couple ways, so could you tell me which one of the following plans is more in line with your thinking?

1) There are multiple generic functions (i.e., `knitr_objective`, `knitr_constraints`, etc.), all with dispatches for `optimization_model`. The key argument is the model and users control output by selecting an appropriate generic.
2) There are just two generic functions (say, `knitr_math` and `latex_math`) that dispatch to methods for `optimization_model`, `model_objective`, and `model_constraint`. Users control output by supplying an appropriate argument.

**Comment by dirkschumacher** [comment]
Both approaches seem to be viable. I would tend towards `knitr_objective`, `knitr_constraints`, etc. dispatching on `optimization_model`.

We still need to store the original contraint expression somewhere :)

**Comment by harryprince** [comment]
it seems a very promising function!

**Comment by dirkschumacher** [comment]
Thanks for your work again. But I am closing the PR as I would like to rework some of the internals of `ompr`

**Pull request closed without merging**
