### PR TITLE
Ompr v1

### PR DESCRIPTION
**Pull request by dirkschumacher**
Towards a new `MIPModel`. It is currently named `MIPModel2`.

### CODE REVIEW

**Comment by sbmack** [comment]
> Towards a new `MIPModel`. It is currently named `MIPModel2`.

Dirk, I am sort of confused.  So MIPModel2 is a new branch from MIPModel with MILPModel being set aside?  Is there a link with MIPModel2 formulation information and examples available for MIPModel2?  Thanks, SteveM

**Comment by dirkschumacher** [comment]
> Dirk, I am sort of confused. So MIPModel2 is a new branch from MIPModel with MILPModel being set aside? Is there a link with MIPModel2 formulation information and examples available for MIPModel2? Thanks, SteveM

Well, if everything works, there will be a new `MIPModel` which is near 100% backwards compatible. It won't affect `MILPModel`. As of right know, I would like to make that new version of `MIPModel` good enough also for larger models, such that we can deprecate `MILModel`. I believe the vectorized semantics just cause too many problems. But that is another discussion and not part of that PR.

**Comment by sbmack** [comment]
> Well, if everything works, there will be a new `MIPModel` which is near 100% backwards compatible. It won't affect `MILPModel`. As of right know, I would like to make that new version of `MIPModel` good enough also for larger models, such that we can deprecate `MILModel`. I believe the vectorized semantics just cause too many problems. But that is another discussion and not part of that PR.

Thanks for the update.  Agree about the problematic vectorized semantics in MILPModel.  Ideally, an updated constraint function in MIPModel2 would accommodate sparse formulations, (row, column, value).  I am not a developer, but it seems like the dplyr pivot_longer function could pre-process the constraint set in rcv format and that could be passed to MIPModel2.

Again, appreciate your efforts.  SteveM

**Comment by dirkschumacher** [comment]
>  Ideally, an updated constraint function in MIPModel2 would accommodate sparse formulations, (row, column, value). I am not a developer, but it seems like the dplyr pivot_longer function could pre-process the sparse constraint set in rcv format and that could be passed to MIPModel2.
@sbmack can you elaborate a bit what you mean exactly? Ideally post that in the Ideas category of the [discussions](https://github.com/dirkschumacher/ompr/discussions). Appreciate your input!

**Comment by sbmack** [comment]
> @sbmack can you elaborate a bit what you mean exactly? Ideally post that in the Ideas category of the [discussions](https://github.com/dirkschumacher/ompr/discussions). Appreciate your input!

Thanks for the reply.  Idea posted in the Ideas category of the Discussions section.  SteveM

**Pull request merged**
