### PR TITLE
Not solving the issue yet

### PR DESCRIPTION
**Pull request by masalmon**
In this PR I

* added a code of conduct

* changed the config file for Appveyor. However in https://ci.appveyor.com/project/masalmon/ompr/build/1.0.2/job/cwanpjfptohv7xcc I now get

```
ERROR: dependency 'ompr' is not available for package 'ompr.roi'
* removing 'c:/RLibrary/ompr.roi'
Error: Command failed (1)
Execution halted
```

so I'll now look for how to deal with this.

### CODE REVIEW

**Comment by masalmon** [comment]
Note that I added my own secure Github PAT so you should change this, see https://github.com/krlmlr/r-appveyor/issues/33

**Comment by masalmon** [comment]
Now the build is no longer failing because of the unit tests, it is failing because of 3 warnings due to undocumented things. Cf https://github.com/dirkschumacher/ompr/issues/40

**Comment by dirkschumacher** [comment]
Thanks a lot again for figuring out what the problem was. I would suggest two options:
* Either, I pick the changes and make the commits myself
* Or, you split the PR into two separate PRs (one for the Code of Conduct and one for Appveyor). Please then use imperative style commit message and just one commit per change. I would like to keep the commit history as clean as possible.

**Comment by masalmon** [comment]
I'll let you pick the changes because I won't have much time. 😊

**Pull request closed without merging**
